#!/bin/sh

start() {
    if ! pgrep -f $1 ;
    then
        "$@"&
    fi
}

# load X colors
start xrdb $HOME/.config/awesome/Xresources

# apps
start /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
start xsetroot -cursor_name left_ptr
start nm-applet
start setxkbmap us,ir -option 'grp:alt_shift_toggle'
start ksuperkey -e 'Super_L=Alt_L|F1'
# pause mpv if there are open windows
start feh --bg-fill -z ~/.config/Wallpaper/
# compositor
start picom --config=$HOME/.config/awesome/theme/picom.conf
