#!/usr/bin/env bash

SC='/usr/local/bin/dwmblocks-scripts/batteryH'
IC=$(sh $SC --icon)
FG=$(sh $SC --fg)
BG=$(sh $SC --bg)

if [[ ! $(acpi -b | grep -i battery) ]]; then
	exit 0
else
	if [[ ! $(acpi -a|grep -i adapter|grep -i on-line) ]]; then
		printf "^c$BG^$IC^c$FG^"
	else
		printf "^c$BG^$IC^c$FG^"
	fi
	echo "$(acpi | sed "s/,//g" | awk '{print $4}' | tr -d "\n")"
fi
