#!/bin/bash


is_eth_used=$(cat /sys/class/net/l*/carrier)
is_wlan_used=$(cat /sys/class/net/wl*/carrier)

echo -n "^c#88c0d0^"

if  [ "$is_eth_used" -eq 1 ]; then    # wired network is carrying
  icon=" ^d^ " #uF6FF
elif  [ "$is_wlan_used" -eq 1 ]; then # wireless network is carrying
  icon=" ^d^" #uF1EB
else
  icon=" ^d^" #uf128 # no network
fi

echo -n $icon

case $BLOCK_BUTTON in
          1) setsid -f alacritty -e nmtui;;
esac
