#!/usr/bin/env bash
#

red="#FF3131"
purple="#9457EB"
green="#39FF14"
blue="#4D4DFF"
bblue="#89CFF0"
orange="#F6890A"
yellow="#CCFF00"
cyan="#00FEFC"
teal="#43BBB6"
black="#000000"

grey="#B0B6B6"
echo "^b$black^^c$cyan^=^d^^b$cyan^^c$black^$(pacman -Q | wc -l)^d^"
