#!/usr/bin/env bash

black=#121111
green=#8fa176
white=#dbdfdf
grey=#212126
darkblue=#7d95ae
red=#ca5a5e
blue=#809fbe
yellow=#d8b170

 SSID=$(iwgetid -r)
	case "$(cat /sys/class/net/wl*/operstate 2>/dev/null)" in
	up) printf "\x02^c$black^^b$blue^ 󰤨 ^d^%s""^c$blue^^b$grey^ $SSID ^b$black^" ;;
	down) printf "\x02^c$black^^b$blue^ 󰤯 ^d^%s""^c$blue^^b$grey^ Disconnected ^b$black^" ;;
	esac
