# autogenerated by txs
#include:pict2e
\csname{arg1}#S
\earc#S
\elliparc#S
\ellipse#S
\pIIe#S
\pIIeearc#S
\pIIeelliparc[opt]{arg1}{arg2}{arg3}{arg4}{arg5}{arg6}#S
\pIIeelliparc{arg1}{arg2}{arg3}{arg4}{arg5}{arg6}#S
\pIIeellipse#S
\\pIIeelliparc#S
