#!/usr/bin/env bash

DIR="$HOME/.config/bspwm"

rofi \
	-show drun \
	-modi run,drun,window,filebrowser \
	-no-lazy-grab \
	-scroll-method 0 \
	-drun-match-fields all \
	-drun-display-format "{name}" \
	-no-drun-show-actions \
	-terminal alacritty \
	-theme "$DIR"/rofi/Theme.rasi
