#!/bin/sh

#####################################################
#   ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗   #
#   ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║   #
#   ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║   #
#   ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║   #
#   ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║   #
#   ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝   #                                    
##################### By: Mahdi ####################


export PATH="${PATH}:${HOME}/.config/bspwm/bin"

export QT_QPA_PLATFORMTHEME="qt5ct"


export _JAVA_AWT_WM_NONREPARENTING=1



killall -99 polybar  

if [[ $(xrandr -q | grep 'HDMI-A-0 connected') ]]; then
    bspc monitor HDMI-A-0 -d I II III IV V VI VII IIX IX X
    polybar --config=~/.config/bspwm/polybar/config.ini --reload example2 &
else
    bspc monitor eDP -d I II III IV V VI VII IIX IX X
    polybar --config=~/.config/bspwm/polybar/config.ini --reload example &
fi





# ##############################################################################
# #                                  FUNCTIONS                                 # 
# ##############################################################################

# Credits to 6gk/polka
rule() { bspc rule -a "$@" & }
config() { bspc config "$@" & }

# ##############################################################################
# #                                AUTOSTART APPS                              #
# ##############################################################################

# Run keybindings daemon.
pgrep -x sxhkd > /dev/null || sxhkd &
mpd &
dunst --config $HOME/.config/dunst/dunstrc &
picom --experimental-backend --config $HOME/.config/bspwm/picom.conf &
eww daemon &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
xfce4-power-manager &
ksuperkey -e 'Super_L=Alt_L|F1' &
bspfloat &
feh --no-fehbg --bg-fill ~/Pictures/Wallpaper/0WEBEiZ.png
xsetroot -cursor_name left_ptr &

# ##############################################################################
# #                                 WINDOW RULES                               #
# ##############################################################################


# ##############################################################################
# #                            GENERAL CONFIGURATION                           #
# ##############################################################################


config top_padding 28
config border_width 2
config left_padding 0
config right_padding 0
config button_padding 0
config window_gap 2
config split_ratio 0.50

config borderless_monocle true
config gapless_monocle true
config focus_follows_pointer true

bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"
#pkill borders ; borders &
bspc config external_rules_command ''

setxkbmap us,ir -option 'grp:alt_shift_toggle' &

bspc rule -a 'MATLAB R2018b' state=floating &
bspc rule -a 'Matplotlib' state=floating &
bspc rule -a 'Python3' state=floating &
bspc rule -a 'Figure' state=floating &
bspc rule -a 'MyNotes' state=floating &

