#  █████╗ ██╗      █████╗  ██████╗██████╗ ██╗████████╗████████╗██╗   ██╗    
# ██╔══██╗██║     ██╔══██╗██╔════╝██╔══██╗██║╚══██╔══╝╚══██╔══╝╚██╗ ██╔╝    
# ███████║██║     ███████║██║     ██████╔╝██║   ██║      ██║    ╚████╔╝     
# ██╔══██║██║     ██╔══██║██║     ██╔══██╗██║   ██║      ██║     ╚██╔╝      
# ██║  ██║███████╗██║  ██║╚██████╗██║  ██║██║   ██║      ██║      ██║       
# ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝   ╚═╝      ╚═╝      ╚═╝                                                                          

# https://github.com/L4ZYP4CM4N/DOTFILES

window:
  padding:
    x: 0
    y: 0
  class:
    instance: Alacritty
    general: Alacritty
  opacity: 0.85

scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: FiraCode Nerd Font
    style:  Regular 
  bold:
    family: FiraCode Nerd Font
    style:  Bold
  italic:
    family: FiraCode Nerd Font
    style:  Italic
  bold_italic:
    family: FiraCode Nerd Font
    style: Bold Italic
  size: 12 

draw_bold_text_with_bright_colors: true

cursor:
  style:
    shape: Block # Block, Beam, Underline
    blinking: Off
    blinking-interval: 750

# Available themes are: 
 # catppuccin.yaml 
 # cake.yaml 
 # tokyo.yaml.yaml 
 # tokyo-night.yaml 
 # argonaut.yaml # favorite
 # dracula.yaml 
 # hard FiraCodeer.yaml 
 # horizon-dark.yaml 
 # moonlight.yaml 
 # omni.yaml 
 # palenight.yaml 
 # snazzy.yaml 

import:
  - ~/.config/alacritty/themes/synthwave.yml

selection:
  save_to_clipboard: true

shell:
  program: /usr/bin/zsh

key_bindings:
  - { key: Return, mods: Control|Shift, action: SpawnNewInstance }

  - { key: Key0, mods: Control, action: ResetFontSize }

  - { key: Equals, mods: Control, action: IncreaseFontSize }

  - { key: Minus, mods: Control, action: DecreaseFontSize }

# shift + control + space = view mode
# in view mode + v = select
